from datetime import datetime
from typing import List, Optional
import uuid
from pydantic import Field

from app.models.enums import AlertSeverityEnum, AlertSourceEnum, AlertStatusEnum
from app.schemas.common import BaseSchema


class SystemAlertResponse(BaseSchema):
    """
    Operational system alert response generated by ML engines or rule thresholds.
    """
    alert_id: uuid.UUID = Field(..., description="Unique alert identifier")
    project_id: str = Field(..., description="Target project identifier")
    report_month: str = Field(..., description="Month epoch when alert was triggered (YYYY-MM)")
    alert_code: str = Field(..., description="Machine-readable rule or signal code")
    severity: AlertSeverityEnum = Field(..., description="Severity level: LOW, MEDIUM, HIGH, CRITICAL")
    alert_source: AlertSourceEnum = Field(..., description="Origin source: ML_ENGINE, RULE_ENGINE, EXECUTION_SURVEILLANCE, PREDICTIVE_ML")
    message: str = Field(..., description="Human-readable warning message")
    status: AlertStatusEnum = Field(..., description="Resolution status: ACTIVE, ACKNOWLEDGED, RESOLVED")
    acknowledged_by: Optional[str] = Field(None, description="Username of acknowledging officer")
    acknowledged_at: Optional[datetime] = Field(None, description="Timestamp of acknowledgement")
    created_at: Optional[datetime] = Field(None, description="Creation timestamp")


class PaginatedAlertsResponse(BaseSchema):
    """
    Standard paginated response wrapper for system alert records.
    """
    items: List[SystemAlertResponse] = Field(..., description="List of alert records")
    page: int = Field(..., description="Current page number (1-indexed)")
    page_size: int = Field(..., description="Items per page")
    total: int = Field(..., description="Total count of matching alerts")
